/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_simalliance_openmobileapi_assdterminal_AssdTerminal */

#ifndef _Included_org_simalliance_openmobileapi_assdterminal_AssdTerminal
#define _Included_org_simalliance_openmobileapi_assdterminal_AssdTerminal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_simalliance_openmobileapi_assdterminal_AssdTerminal
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_simalliance_openmobileapi_assdterminal_AssdTerminal_close
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_assdterminal_AssdTerminal
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_simalliance_openmobileapi_assdterminal_AssdTerminal_open
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_assdterminal_AssdTerminal
 * Method:    isPresent
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_simalliance_openmobileapi_assdterminal_AssdTerminal_isPresent
  (JNIEnv *, jobject);

/*
 * Class:     org_simalliance_openmobileapi_assdterminal_AssdTerminal
 * Method:    transmit
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_org_simalliance_openmobileapi_assdterminal_AssdTerminal_transmit
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
